<?php
$LP = [
  'slug'   => 'altbausanierung-nuernberg.php',
  'quelle' => 'lp-altbau',
  'title'  => 'Elektro-Altbausanierung Nürnberg · Festpreis vom Fachbetrieb | OH Haustechnik',
  'meta'   => 'Elektrik im Altbau erneuern lassen in Nürnberg und Umgebung: neue Leitungen, Zählerschrank, Sicherheit nach Norm. Kostenloses Festpreis-Angebot in 2 Minuten.',
  'h1'     => 'Elektro-Altbausanierung im Raum Nürnberg – sicher, sauber, zum Festpreis',
  'sub'    => 'Alte Leitungen, zu wenig Steckdosen, kein FI-Schutz? Wir bringen die Elektrik Ihres Altbaus auf den neuesten Stand – ohne Baustellenchaos, mit klarem Festpreis.',
  'cta'    => 'Kostenloses Festpreis-Angebot',
  'badges' => ['Rückmeldung am selben Tag', 'Faire Festpreise', 'Saubere Ausführung', 'Lokal & persönlich'],
  'schritte' => [
    ['Anfrage senden', 'In 2 Minuten Eckdaten zu Ihrem Altbau angeben – ganz unverbindlich.'],
    ['Angebot erhalten', 'Sie bekommen schnell ein transparentes Festpreis-Angebot.'],
    ['Termin & Umsetzung', 'Wir sanieren termintreu und in einem Zug – ein Ansprechpartner bis zur Abnahme.'],
  ],
  'leistungen' => [
    ['fa-bolt', 'Neue Elektroinstallation', 'Komplette Erneuerung der Leitungen, Dosen und Verteilung nach aktueller Norm.'],
    ['fa-gauge-high', 'Zählerschrank & Verteiler', 'Moderner Zählerschrank, FI-Schutzschalter, mehr Sicherheit für Ihre Familie.'],
    ['fa-house-signal', 'Smart-Home-ready', 'Auf Wunsch gleich vorbereitet für Smart Home, Wallbox und Netzwerk.'],
  ],
  'faq' => [
    ['Woran erkenne ich, dass die Elektrik im Altbau erneuert werden muss?',
     'Fünf Anzeichen sind eindeutig: Schraubsicherungen statt Sicherungsautomaten, kein FI-Schutzschalter im Verteiler, zweiadrige Leitungen ohne grün-gelben Schutzleiter, stoffummantelte Leitungen aus der Zeit vor 1965 und Steckdosen ohne Schutzkontakt. Kommt dazu, dass regelmäßig Sicherungen auslösen oder Steckdosenleisten das Fehlen von Anschlüssen ausgleichen müssen, ist die Anlage überlastet.'],
    ['Muss ich während der Sanierung ausziehen?',
     'In aller Regel nicht. Wir arbeiten in bewohnten Wohnungen raumweise: In den Räumen, an denen gerade nicht gearbeitet wird, bleibt der Strom an, und abends ist die Wohnung wieder nutzbar. Komplett ohne Strom sind Sie nur beim Tausch des Zählerschranks, und das sind wenige Stunden an einem Tag, den wir vorher mit Ihnen abstimmen.'],
    ['Muss bei einer Sanierung immer der Zählerschrank erneuert werden?',
     'Nicht immer, aber häufig. Entspricht der vorhandene Zählerschrank nicht der VDE-AR-N 4100, verlangen die Netzbetreiber bei wesentlichen Änderungen an der Anlage eine Anpassung. Seit 2019 gehört dazu der APZ, der Anschlussplatz für Zusatzanwendungen. Alte Verteilungen mit Schraubsicherungen und ohne Fehlerstromschutz erfüllen das nicht. Wir prüfen das beim Ortstermin und sagen Ihnen vorher, ob es nötig ist.'],
    ['Sind FI-Schutzschalter im Altbau Pflicht?',
     'Für die bestehende Anlage gilt Bestandsschutz. Sobald ein Stromkreis aber erneuert oder neu errichtet wird, greift die aktuelle DIN VDE 0100-410, und die verlangt für Steckdosenstromkreise in Wohnungen einen Fehlerstromschutzschalter mit 30 mA. Bei einer Sanierung kommt der FI-Schutz also in jedem Fall mit.'],
    ['Was ist der APZ und brauche ich den?',
     'Der Anschlussplatz für Zusatzanwendungen ist ein reservierter Bereich im Zählerschrank, den die VDE-AR-N 4100 seit 2019 fordert. Dort sitzen später Steuereinrichtungen für Wallbox, Wärmepumpe oder Photovoltaik. Wenn Sie den Zählerschrank ohnehin erneuern, wird der APZ mit eingebaut – das erspart Ihnen den zweiten Umbau, sobald Sie ein E-Auto oder eine PV-Anlage anschaffen.'],
    ['Bekomme ich einen Nachweis über die Arbeiten?',
     'Ja. Nach Abschluss führen wir die Erstprüfung nach DIN VDE 0100-600 durch und übergeben Ihnen das Messprotokoll. Das brauchen Sie für Ihre Gebäudeversicherung und beim Verkauf oder der Vermietung der Immobilie.'],
    ['Kann ich die Sanierung in Abschnitten machen?',
     'Ja, das ist bei bewohnten Altbauten oft der sinnvollere Weg. Üblich ist, zuerst Zählerschrank und Hauptleitungen zu erneuern und danach Wohnbereich für Wohnbereich nachzuziehen. Wir planen die Abschnitte so, dass jeder für sich abgeschlossen und sicher ist und keine Arbeit doppelt anfällt.'],
    ['Wie schnell können Sie starten?',
     'Nach dem Vor-Ort-Termin nennen wir Ihnen einen verbindlichen Starttermin, meist innerhalb weniger Wochen.'],
  ],
];
include __DIR__ . '/includes/lp-render.php';
