<?php
$LP = [
  'slug'   => 'komplettsanierung-nuernberg.php',
  'quelle' => 'lp-komplettsanierung',
  'title'  => 'Elektro-Komplettsanierung Nürnberg · Wohnung & Haus zum Festpreis | OH Haustechnik',
  'meta'   => 'Wohnung oder Haus komplett sanieren in Nürnberg, Fürth & Erlangen: gesamte Elektrik neu – Leitungen, Zählerschrank, Unterverteilung, Smart-Home-ready. Kostenloses Festpreis-Angebot in 2 Minuten.',
  'h1'     => 'Elektro-Komplettsanierung für Wohnung & Haus im Raum Nürnberg',
  'sub'    => 'Sie modernisieren komplett? Wir übernehmen die gesamte Elektrik – von der Planung bis zur Abnahme. Ein Ansprechpartner, ein klarer Festpreis, termintreu und sauber.',
  'cta'    => 'Kostenloses Festpreis-Angebot',
  'badges' => ['Komplett aus einer Hand', 'Klarer Festpreis', 'Termintreu & sauber', 'Nürnberg · Fürth · Erlangen'],
  'schritte' => [
    ['Projekt schildern', 'In 2 Minuten Eckdaten zu Wohnung/Haus angeben – Größe, Umfang, Zeitrahmen. Unverbindlich.'],
    ['Festpreis erhalten', 'Sie bekommen ein transparentes Festpreis-Angebot für die komplette Elektrik – ohne versteckte Kosten.'],
    ['Sauber umgesetzt', 'Wir sanieren abschnittsweise, termintreu und ordentlich – Sie haben einen festen Ansprechpartner.'],
  ],
  'leistungen' => [
    ['fa-bolt', 'Komplette Elektrik neu', 'Alle Leitungen, Dosen und Schalter erneuert – nach aktueller Norm, sicher für die ganze Familie.'],
    ['fa-gauge-high', 'Zählerschrank & Unterverteilung', 'Moderner Zählerschrank, neue Unterverteilung und FI-Schutz – die Basis für sorgenfreies Wohnen.'],
    ['fa-house-signal', 'Smart-Home & Netzwerk ready', 'Auf Wunsch gleich vorbereitet für KNX, Smart Home, Wallbox und schnelles Netzwerk.'],
    ['fa-list-check', 'Planung & Abnahme', 'Wir planen den gesamten Umfang, koordinieren die Gewerke-Schnittstellen und übergeben dokumentiert.'],
    ['fa-shield-halved', 'Sicherheit nach Norm', 'Mess- und Prüfprotokolle inklusive – alles normgerecht und nachvollweisbar.'],
    ['fa-handshake', 'Ein Ansprechpartner', 'Vom ersten Gespräch bis zur Schlussrechnung betreut Sie eine feste Person.'],
  ],
  'faq' => [
    ['In welcher Reihenfolge läuft eine Komplettsanierung ab?',
     'Zuerst der Hausanschluss und der Zählerschrank, denn davon hängt alles Weitere ab. Dann die Steigleitungen und Unterverteilungen, danach die Stromkreise Raum für Raum, zuletzt Schalter, Steckdosen und Leuchten. Am Ende steht die Erstprüfung nach DIN VDE 0100-600 mit Messprotokoll. Diese Reihenfolge ist keine Vorliebe, sondern technisch notwendig: Wer die Räume vor der Verteilung macht, arbeitet doppelt.'],
    ['Was muss bei einer Komplettsanierung beim Netzbetreiber angemeldet werden?',
     'Ein neuer oder geänderter Zählerschrank ist beim zuständigen Netzbetreiber anzumelden, ebenso Wallbox, Wärmepumpe und Photovoltaik. Anlagen über 4,2 kW gelten seit 2024 nach § 14a EnWG als steuerbare Verbrauchseinrichtungen und müssen zusätzlich registriert und steuerbar sein. Die Anmeldungen übernehmen wir für Sie und stimmen die Termine mit dem Zählermonteur ab.'],
    ['Lohnt es sich, gleich für Wallbox, PV und Smart Home vorzubereiten?',
     'Ja, und zwar deutlich. Ein Leerrohr zum Stellplatz oder ein zusätzliches Kabel zum Dach kostet während der Sanierung fast nichts, weil die Wände ohnehin offen sind. Nachträglich bedeutet dasselbe Kabel Stemmen, Verschließen und Streichen. Wir planen deshalb Reserveplätze im Zählerschrank, den APZ und Leerrohre für spätere Erweiterungen standardmäßig mit ein – nutzen müssen Sie sie nicht.'],
    ['Wie viele Steckdosen und Stromkreise sind sinnvoll?',
     'Als Orientierung dient die DIN 18015-2 mit Ausstattungswerten für Wohngebäude. In der Praxis planen wir Küche, Bad, Wohnzimmer und Arbeitsplätze mit eigenen Stromkreisen, damit nicht die halbe Wohnung dunkel wird, wenn eine Sicherung fällt. Bei Steckdosen gilt: Was Sie beim Planen für übertrieben halten, ist nach zwei Jahren genau richtig. Nachrüsten kostet ein Vielfaches.'],
    ['Übernehmt ihr die ganze Wohnung bzw. das ganze Haus?',
     'Ja. Die komplette Elektrik aus einer Hand – Leitungen, Verteilung, Smart-Home-Vorbereitung, Anmeldung beim Netzbetreiber und Abnahme mit Protokoll.'],
    ['Wie schnell könnt ihr starten?',
     'Nach einem kurzen Vor-Ort-Termin nennen wir einen verbindlichen Starttermin – bei größeren Projekten planen wir gemeinsam den passenden Zeitrahmen.'],
    ['In welchem Gebiet arbeitet ihr?',
     'Nürnberg, Fürth, Erlangen, Schwabach und der Umkreis bis etwa 35 Kilometer.'],
  ],
];
include __DIR__ . '/includes/lp-render.php';
