<?php
$LP = [
  'slug'   => 'wohnung-elektro-sanieren-nuernberg.php',
  'quelle' => 'lp-sanierung',
  'title'  => 'Wohnung & Haus Elektro sanieren Nürnberg · Festpreis vom Fachbetrieb | OH Haustechnik',
  'meta'   => 'Elektrik der Wohnung oder des Hauses erneuern in Nürnberg, Fürth & Erlangen: neue Leitungen, Zählerschrank, Unterverteilung, FI-Schutz, Smart-Home-ready. Klarer Festpreis – Sie sagen uns die Größe, wir kalkulieren. Angebot in 2 Minuten.',
  'h1'     => 'Wohnung & Haus in Nürnberg <span class="amber">elektrisch sanieren</span>',
  'sub'    => 'Sie nennen uns Zimmerzahl oder Fläche – wir kalkulieren Ihren Festpreis. Komplette Elektrik neu: Leitungen, Verteilung, Smart-Home-ready.',
  'cta'    => 'Festpreis-Angebot anfordern',
  'preis_hinweis' => 'Richtwert 6.000–12.000 € je nach Größe · Festpreis nach kurzem Vor-Ort-Termin',
  'preis_range' => '€€',
  'badges' => ['Klarer Festpreis', 'Sie sagen die Größe – wir kalkulieren', 'Sauber & termintreu', 'Nürnberg · Fürth · Erlangen'],
  'schritte' => [
    ['Anfrage in 2 Min', 'Zimmerzahl bzw. Fläche, Zustand und Wunsch-Zeitraum angeben – unverbindlich und kostenlos.'],
    ['Festpreis erhalten', 'Wir kalkulieren auf Basis Ihrer Angaben und nennen einen transparenten Festpreis – ohne versteckte Kosten.'],
    ['Sauber umgesetzt', 'Termintreu, ordentlich und mit fester Ansprechperson – wir räumen hinter uns auf.'],
  ],
  'leistungen' => [
    ['fa-bolt', 'Komplette Elektrik neu', 'Alle Leitungen, Dosen und Schalter nach aktueller Norm – sicher für viele Jahre.'],
    ['fa-gauge-high', 'Zählerschrank & Unterverteilung', 'Moderner Zählerschrank, neue Unterverteilung und FI-Schutz.'],
    ['fa-house-signal', 'Smart-Home & Netzwerk', 'Auf Wunsch direkt vorbereitet für Smart Home, schnelles Netzwerk und Wallbox.'],
    ['fa-ruler-combined', 'Preis nach Ihrer Größe', 'Sie geben Zimmerzahl/Fläche an – wir kalkulieren passgenau, statt Pauschalen zu raten.'],
    ['fa-shield-halved', 'Sicherheit nach Norm', 'Mess- und Prüfprotokolle inklusive – alles normgerecht dokumentiert.'],
    ['fa-handshake', 'Ein Ansprechpartner', 'Vom ersten Gespräch bis zur Schlussrechnung betreut Sie eine feste Person.'],
  ],
  'faq' => [
    ['Was kostet es, eine Wohnung elektrisch zu sanieren?',
     'Eine komplette Elektro-Sanierung beginnt bei rund 6.000 € für eine kleinere Wohnung. Den Preis bestimmen vor allem drei Dinge: die Zahl der Stromkreise, ob der Zählerschrank mit erneuert werden muss und ob unter Putz gearbeitet wird oder aufputz. Nach einem kurzen Ortstermin bekommen Sie einen verbindlichen Festpreis, keine Schätzung.'],
    ['Ich wohne zur Miete – wer bezahlt die Elektro-Sanierung?',
     'Die Erneuerung der Elektroinstallation ist Sache des Eigentümers, nicht des Mieters. Sie zählt als Instandsetzung oder Modernisierung nach § 555b BGB. Als Mieter können Sie den Vermieter darauf hinweisen, dass die Anlage nicht mehr dem Stand der Technik entspricht – gerade fehlender Fehlerstromschutz ist ein starkes Argument. Wir erstellen Ihnen dafür gerne ein Angebot, das Sie weiterreichen können.'],
    ['Eigentumswohnung: was darf ich allein entscheiden?',
     'Alles innerhalb Ihrer Wohnung ab der Abzweigung von der Steigleitung ist Sondereigentum – Leitungen, Dosen, Schalter und meist auch die Unterverteilung können Sie ohne Beschluss erneuern lassen. Die Steigleitungen im Treppenhaus, der Hausanschlusskasten und der Zählerschrank gehören dagegen zum Gemeinschaftseigentum. Muss dort etwas gemacht werden, braucht es einen Beschluss der Eigentümergemeinschaft. Wir sagen Ihnen beim Ortstermin, in welchen Bereich Ihr Vorhaben fällt.'],
    ['Wie viel Schmutz und Lärm entsteht?',
     'Das hängt an der Verlegeart. Unter Putz bedeutet Schlitze stemmen, also Staub und Lärm über mehrere Tage; wir stellen Staubschutzwände auf und saugen direkt am Gerät ab. Deutlich schonender sind Kabelkanäle oder das Verlegen in vorhandenen Leerrohren – nicht immer möglich, aber wir prüfen es immer zuerst. Das Verschließen und Streichen der Schlitze gehört nicht zu unserer Leistung; ob Sie das selbst machen oder einen Maler brauchen, klären wir vorher.'],
    ['Reicht es, nur die Steckdosen zu tauschen?',
     'Wenn hinter der Steckdose eine zweiadrige Leitung ohne Schutzleiter liegt, bringt der Tausch nichts – die neue Steckdose sieht besser aus, ist aber genauso ungeschützt. Sinnvoll ist der reine Tausch nur, wenn Leitungen und Verteilung in Ordnung sind. Wir messen das vorab, statt Ihnen etwas zu verkaufen, das nichts bringt.'],
    ['Macht ihr Wohnungen und Häuser jeder Größe?',
     'Ja – von der 2-Zimmer-Wohnung bis zum kompletten Einfamilienhaus, die gesamte Elektrik aus einer Hand.'],
    ['In welchem Gebiet arbeitet ihr?',
     'Nürnberg, Fürth, Erlangen, Schwabach und der Umkreis bis etwa 35 Kilometer, darunter Zirndorf, Stein, Feucht, Wendelstein, Lauf und Roth.'],
  ],
];
include __DIR__ . '/includes/lp-render.php';
